/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MedsRouteImport } from './routes/meds'
import { Route as HealthRouteImport } from './routes/health'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyIdRouteImport } from './routes/verify.$id'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MedsRoute = MedsRouteImport.update({
  id: '/meds',
  path: '/meds',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/certificates': typeof CertificatesRoute
  '/emergency': typeof EmergencyRoute
  '/health': typeof HealthRoute
  '/meds': typeof MedsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/queue': typeof QueueRoute
  '/recovery': typeof RecoveryRoute
  '/reminders': typeof RemindersRoute
  '/tips': typeof TipsRoute
  '/visit': typeof VisitRoute
  '/welcome': typeof WelcomeRoute
  '/verify/$id': typeof VerifyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/certificates': typeof CertificatesRoute
  '/emergency': typeof EmergencyRoute
  '/health': typeof HealthRoute
  '/meds': typeof MedsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/queue': typeof QueueRoute
  '/recovery': typeof RecoveryRoute
  '/reminders': typeof RemindersRoute
  '/tips': typeof TipsRoute
  '/visit': typeof VisitRoute
  '/welcome': typeof WelcomeRoute
  '/verify/$id': typeof VerifyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/certificates': typeof CertificatesRoute
  '/emergency': typeof EmergencyRoute
  '/health': typeof HealthRoute
  '/meds': typeof MedsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/queue': typeof QueueRoute
  '/recovery': typeof RecoveryRoute
  '/reminders': typeof RemindersRoute
  '/tips': typeof TipsRoute
  '/visit': typeof VisitRoute
  '/welcome': typeof WelcomeRoute
  '/verify/$id': typeof VerifyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/ai-chat'
    | '/auth'
    | '/bookings'
    | '/certificates'
    | '/emergency'
    | '/health'
    | '/meds'
    | '/notifications'
    | '/profile'
    | '/queue'
    | '/recovery'
    | '/reminders'
    | '/tips'
    | '/visit'
    | '/welcome'
    | '/verify/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/ai-chat'
    | '/auth'
    | '/bookings'
    | '/certificates'
    | '/emergency'
    | '/health'
    | '/meds'
    | '/notifications'
    | '/profile'
    | '/queue'
    | '/recovery'
    | '/reminders'
    | '/tips'
    | '/visit'
    | '/welcome'
    | '/verify/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/ai-chat'
    | '/auth'
    | '/bookings'
    | '/certificates'
    | '/emergency'
    | '/health'
    | '/meds'
    | '/notifications'
    | '/profile'
    | '/queue'
    | '/recovery'
    | '/reminders'
    | '/tips'
    | '/visit'
    | '/welcome'
    | '/verify/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AiChatRoute: typeof AiChatRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  CertificatesRoute: typeof CertificatesRoute
  EmergencyRoute: typeof EmergencyRoute
  HealthRoute: typeof HealthRoute
  MedsRoute: typeof MedsRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  QueueRoute: typeof QueueRoute
  RecoveryRoute: typeof RecoveryRoute
  RemindersRoute: typeof RemindersRoute
  TipsRoute: typeof TipsRoute
  VisitRoute: typeof VisitRoute
  WelcomeRoute: typeof WelcomeRoute
  VerifyIdRoute: typeof VerifyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meds': {
      id: '/meds'
      path: '/meds'
      fullPath: '/meds'
      preLoaderRoute: typeof MedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  AiChatRoute: AiChatRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  CertificatesRoute: CertificatesRoute,
  EmergencyRoute: EmergencyRoute,
  HealthRoute: HealthRoute,
  MedsRoute: MedsRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  QueueRoute: QueueRoute,
  RecoveryRoute: RecoveryRoute,
  RemindersRoute: RemindersRoute,
  TipsRoute: TipsRoute,
  VisitRoute: VisitRoute,
  WelcomeRoute: WelcomeRoute,
  VerifyIdRoute: VerifyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
